/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */

/**
 *
 * @author Talal
 */
public class GUI extends javax.swing.JFrame {

    /**
     * Creates new form FW
     */
    public GUI() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        mygroup = new javax.swing.ButtonGroup();
        jLabel1 = new javax.swing.JLabel();
        jLayeredPane1 = new javax.swing.JLayeredPane();
        jLabel2 = new javax.swing.JLabel();
        jTextFieldInferenceR = new javax.swing.JTextField();
        jLabel3 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        jTextFieldBF = new javax.swing.JTextField();
        jLabel5 = new javax.swing.JLabel();
        jTextField1Goal = new javax.swing.JTextField();
        jSeparator2 = new javax.swing.JSeparator();
        jButtonForward = new javax.swing.JButton();
        jButtonBackward = new javax.swing.JButton();
        jTextFieldAnswerBD = new javax.swing.JTextField();
        jToolBar1 = new javax.swing.JToolBar();
        jTextFieldAnswerFD1 = new javax.swing.JTextField();
        jLabel6 = new javax.swing.JLabel();
        jLabel7 = new javax.swing.JLabel();
        jLabel8 = new javax.swing.JLabel();
        exeFD = new javax.swing.JTextField();
        jLabel9 = new javax.swing.JLabel();
        exeBD = new javax.swing.JTextField();
        jLabel10 = new javax.swing.JLabel();
        jLabel11 = new javax.swing.JLabel();
        jRadioButtonTest2 = new javax.swing.JRadioButton();
        jRadioButtonTest1 = new javax.swing.JRadioButton();
        jRadioButtonTest3 = new javax.swing.JRadioButton();
        jLabel13 = new javax.swing.JLabel();
        jLabel12 = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setTitle("Expert System");

        jLabel1.setFont(new java.awt.Font("Traditional Arabic", 0, 36)); // NOI18N
        jLabel1.setText("Expert System");

        javax.swing.GroupLayout jLayeredPane1Layout = new javax.swing.GroupLayout(jLayeredPane1);
        jLayeredPane1.setLayout(jLayeredPane1Layout);
        jLayeredPane1Layout.setHorizontalGroup(
            jLayeredPane1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 100, Short.MAX_VALUE)
        );
        jLayeredPane1Layout.setVerticalGroup(
            jLayeredPane1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 100, Short.MAX_VALUE)
        );

        jLabel2.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        jLabel2.setText("Inference rules: ");

        jTextFieldInferenceR.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        jTextFieldInferenceR.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jTextFieldInferenceRActionPerformed(evt);
            }
        });

        jLabel3.setForeground(new java.awt.Color(112, 123, 124));
        jLabel3.setText(" X=>Y;R&T=>N");

        jLabel4.setText("Base of facts (BF) initial:");

        jTextFieldBF.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        jTextFieldBF.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jTextFieldBFActionPerformed(evt);
            }
        });

        jLabel5.setText("Goal:");

        jTextField1Goal.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        jTextField1Goal.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jTextField1GoalActionPerformed(evt);
            }
        });

        jSeparator2.setForeground(new java.awt.Color(0, 0, 255));
        jSeparator2.setBorder(javax.swing.BorderFactory.createEmptyBorder(1, 1, 1, 1));
        jSeparator2.setFocusable(true);
        jSeparator2.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N

        jButtonForward.setText("Forward Chaining");
        jButtonForward.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButtonForwardActionPerformed(evt);
            }
        });

        jButtonBackward.setText("Backward Chaining");
        jButtonBackward.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButtonBackwardActionPerformed(evt);
            }
        });

        jTextFieldAnswerBD.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jTextFieldAnswerBDActionPerformed(evt);
            }
        });

        jToolBar1.setBackground(new java.awt.Color(153, 163, 164));
        jToolBar1.setRollover(true);

        jTextFieldAnswerFD1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jTextFieldAnswerFD1ActionPerformed(evt);
            }
        });

        jLabel6.setText("Does KB entails alpha?");

        jLabel7.setText("Does KB entails alpha?");

        jLabel8.setText("Execution time ");

        exeFD.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                exeFDActionPerformed(evt);
            }
        });

        jLabel9.setText("Execution time ");

        exeBD.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                exeBDActionPerformed(evt);
            }
        });

        jLabel10.setForeground(new java.awt.Color(112, 123, 124));
        jLabel10.setText("( msec )");

        jLabel11.setForeground(new java.awt.Color(112, 123, 124));
        jLabel11.setText("( msec )");

        mygroup.add(jRadioButtonTest2);
        jRadioButtonTest2.setText("Test problem2");
        jRadioButtonTest2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jRadioButtonTest2ActionPerformed(evt);
            }
        });

        mygroup.add(jRadioButtonTest1);
        jRadioButtonTest1.setText("Test pronlem1");
        jRadioButtonTest1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jRadioButtonTest1ActionPerformed(evt);
            }
        });

        mygroup.add(jRadioButtonTest3);
        jRadioButtonTest3.setText("Test problem3");
        jRadioButtonTest3.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jRadioButtonTest3ActionPerformed(evt);
            }
        });

        jLabel13.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        jLabel13.setText("Choose the desired test problem or, simply fill the blanks");

        jLabel12.setForeground(new java.awt.Color(112, 123, 124));
        jLabel12.setText(" A;B;D");

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jSeparator2, javax.swing.GroupLayout.PREFERRED_SIZE, 784, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addGroup(layout.createSequentialGroup()
                        .addGap(10, 10, 10)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jTextFieldAnswerFD1, javax.swing.GroupLayout.PREFERRED_SIZE, 295, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jLabel7)
                            .addGroup(layout.createSequentialGroup()
                                .addComponent(jLabel8)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(jLabel10))
                            .addComponent(exeFD, javax.swing.GroupLayout.PREFERRED_SIZE, 153, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(68, 68, 68)
                        .addComponent(jToolBar1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(38, 38, 38)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jTextFieldAnswerBD, javax.swing.GroupLayout.PREFERRED_SIZE, 295, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jLabel6)
                            .addGroup(layout.createSequentialGroup()
                                .addComponent(jLabel9)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(jLabel11))
                            .addComponent(exeBD, javax.swing.GroupLayout.PREFERRED_SIZE, 153, javax.swing.GroupLayout.PREFERRED_SIZE))))
                .addGap(50, 50, 50))
            .addGroup(layout.createSequentialGroup()
                .addGap(352, 352, 352)
                .addComponent(jLabel1, javax.swing.GroupLayout.PREFERRED_SIZE, 341, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
            .addGroup(layout.createSequentialGroup()
                .addGap(73, 73, 73)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(layout.createSequentialGroup()
                                .addGap(207, 207, 207)
                                .addComponent(jButtonForward)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 23, Short.MAX_VALUE)
                                .addComponent(jButtonBackward)
                                .addGap(70, 70, 70))
                            .addGroup(layout.createSequentialGroup()
                                .addComponent(jTextField1Goal)
                                .addGap(170, 170, 170)))
                        .addComponent(jLayeredPane1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(122, 122, 122))
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(jLabel2)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(jLabel13)
                        .addGap(35, 35, 35))
                    .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addComponent(jLabel3)
                            .addComponent(jLabel4, javax.swing.GroupLayout.PREFERRED_SIZE, 148, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jLabel5)
                            .addComponent(jLabel12)
                            .addComponent(jTextFieldInferenceR, javax.swing.GroupLayout.DEFAULT_SIZE, 404, Short.MAX_VALUE)
                            .addComponent(jTextFieldBF))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jRadioButtonTest3)
                            .addComponent(jRadioButtonTest2)
                            .addComponent(jRadioButtonTest1))
                        .addGap(169, 169, 169))))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGap(99, 99, 99)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jLabel2)
                            .addComponent(jLabel13)))
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                        .addGap(21, 21, 21)
                        .addComponent(jLabel1)
                        .addGap(41, 41, 41)))
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGap(31, 31, 31)
                        .addComponent(jRadioButtonTest1))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(12, 12, 12)
                        .addComponent(jLabel3)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(jTextFieldInferenceR, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(15, 15, 15)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jLabel4)
                            .addComponent(jRadioButtonTest2))
                        .addGap(5, 5, 5)
                        .addComponent(jLabel12)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jTextFieldBF, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jRadioButtonTest3))))
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(jLabel5)
                        .addGap(6, 6, 6)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                            .addComponent(jLayeredPane1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addGroup(layout.createSequentialGroup()
                                .addComponent(jTextField1Goal, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                                    .addComponent(jButtonForward)
                                    .addComponent(jButtonBackward))))
                        .addGap(18, 18, 18)
                        .addComponent(jSeparator2, javax.swing.GroupLayout.PREFERRED_SIZE, 2, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jToolBar1, javax.swing.GroupLayout.PREFERRED_SIZE, 125, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addGroup(layout.createSequentialGroup()
                                .addComponent(jLabel7)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(jTextFieldAnswerFD1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(18, 18, 18)
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                                    .addComponent(jLabel8)
                                    .addComponent(jLabel10))
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(exeFD, javax.swing.GroupLayout.PREFERRED_SIZE, 28, javax.swing.GroupLayout.PREFERRED_SIZE)))
                        .addGap(27, 27, 27))
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                        .addGap(187, 187, 187)
                        .addComponent(jLabel6)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(jTextFieldAnswerBD, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(18, 18, 18)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jLabel9)
                            .addComponent(jLabel11))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(exeBD, javax.swing.GroupLayout.PREFERRED_SIZE, 28, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(38, 38, 38))))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void jTextFieldBFActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jTextFieldBFActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jTextFieldBFActionPerformed

    private void jTextField1GoalActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jTextField1GoalActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jTextField1GoalActionPerformed

    private void jButtonForwardActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButtonForwardActionPerformed
        // TODO add your handling code here:
        jTextFieldAnswerFD1.setText(" ");
        exeFD.setText(" ");
        FC.counter=0;
        String a = jTextFieldInferenceR.getText().toString()+";";
        a=a.concat(jTextFieldBF.getText().toString());
        String t= jTextField1Goal.getText().toString();
        
        FC fc= new FC(t, a);
        long start = System.currentTimeMillis();
        jTextFieldAnswerFD1.setText(fc.execute());
        long time= System.currentTimeMillis()-start;
        exeFD.setText(Long.toString(time));
        
     
        
        
        
        
        
    }//GEN-LAST:event_jButtonForwardActionPerformed

    private void jButtonBackwardActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButtonBackwardActionPerformed
        // TODO add your handling code here:
        
        jTextFieldAnswerBD.setText(" ");
        exeBD.setText(" ");
        BC.counter=0;
        BC.counter2=0;
       String a=jTextField1Goal.getText().toString();
       String t= jTextFieldInferenceR.getText().toString()+";";
       t=t.concat(jTextFieldBF.getText().toString());
   
        BC bc= new BC(a, t);
        long start = System.currentTimeMillis();
        jTextFieldAnswerBD.setText(bc.execute());
        long time=System.currentTimeMillis()-start;
        exeBD.setText(Long.toString(time));
        
        
        
        
    }//GEN-LAST:event_jButtonBackwardActionPerformed

    private void jTextFieldAnswerBDActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jTextFieldAnswerBDActionPerformed
        // TODO add your handling code here:
        jTextFieldAnswerBD.setText(" ");
    }//GEN-LAST:event_jTextFieldAnswerBDActionPerformed

    private void jTextFieldAnswerFD1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jTextFieldAnswerFD1ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jTextFieldAnswerFD1ActionPerformed

    private void exeFDActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_exeFDActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_exeFDActionPerformed

    private void exeBDActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_exeBDActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_exeBDActionPerformed

    private void jTextFieldInferenceRActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jTextFieldInferenceRActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jTextFieldInferenceRActionPerformed

    private void jRadioButtonTest1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jRadioButtonTest1ActionPerformed
        // TODO add your handling code here:
         jTextFieldInferenceR.setText("");
        jTextField1Goal.setText("");
        jTextFieldBF.setText("");
        jTextFieldInferenceR.setText("M=>X;F&R=>M;T=>F");
        jTextField1Goal.setText("X");
        jTextFieldBF.setText("T;R");
    }//GEN-LAST:event_jRadioButtonTest1ActionPerformed

    private void jRadioButtonTest2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jRadioButtonTest2ActionPerformed
        // TODO add your handling code here:
         jTextFieldInferenceR.setText("");
        jTextField1Goal.setText("");
        jTextFieldBF.setText("");
        
        jTextFieldInferenceR.setText("A&B=>C;C&D=>F;F&B=>E;F&A=>G;G&F=>B");
        jTextField1Goal.setText("E");
        jTextFieldBF.setText("A;C;D");
        
    }//GEN-LAST:event_jRadioButtonTest2ActionPerformed

    private void jRadioButtonTest3ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jRadioButtonTest3ActionPerformed
        // TODO add your handling code here:
        
         jTextFieldInferenceR.setText("");
        jTextField1Goal.setText("");
        jTextFieldBF.setText("");
        
        jTextFieldInferenceR.setText("P=>Q;L&M=>P;B&L=>M;A&B=>G");
        jTextField1Goal.setText("Q");
        jTextFieldBF.setText("A;B");
    }//GEN-LAST:event_jRadioButtonTest3ActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(GUI.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(GUI.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(GUI.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(GUI.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new GUI().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JTextField exeBD;
    private javax.swing.JTextField exeFD;
    private javax.swing.JButton jButtonBackward;
    private javax.swing.JButton jButtonForward;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel10;
    private javax.swing.JLabel jLabel11;
    private javax.swing.JLabel jLabel12;
    private javax.swing.JLabel jLabel13;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JLabel jLabel9;
    private javax.swing.JLayeredPane jLayeredPane1;
    private javax.swing.JRadioButton jRadioButtonTest1;
    private javax.swing.JRadioButton jRadioButtonTest2;
    private javax.swing.JRadioButton jRadioButtonTest3;
    private javax.swing.JSeparator jSeparator2;
    private javax.swing.JTextField jTextField1Goal;
    private javax.swing.JTextField jTextFieldAnswerBD;
    private javax.swing.JTextField jTextFieldAnswerFD1;
    private javax.swing.JTextField jTextFieldBF;
    private javax.swing.JTextField jTextFieldInferenceR;
    private javax.swing.JToolBar jToolBar1;
    private javax.swing.ButtonGroup mygroup;
    // End of variables declaration//GEN-END:variables
}
